// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/booking.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 1. กำหนดโครงสร้างข้อมูล (Message)
type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_proto_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type ReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TimeSlot      string                 `protobuf:"bytes,3,opt,name=time_slot,json=timeSlot,proto3" json:"time_slot,omitempty"` // เช่น "09:30-11:00"
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`                         // จองล่วงหน้าไม่เกิน 7 วัน
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationRequest) Reset() {
	*x = ReservationRequest{}
	mi := &file_proto_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationRequest) ProtoMessage() {}

func (x *ReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationRequest.ProtoReflect.Descriptor instead.
func (*ReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{1}
}

func (x *ReservationRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ReservationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReservationRequest) GetTimeSlot() string {
	if x != nil {
		return x.TimeSlot
	}
	return ""
}

func (x *ReservationRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "pending" ตามกฎของคุณ [cite: 7, 8]
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationResponse) Reset() {
	*x = ReservationResponse{}
	mi := &file_proto_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationResponse) ProtoMessage() {}

func (x *ReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationResponse.ProtoReflect.Descriptor instead.
func (*ReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{2}
}

func (x *ReservationResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReservationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReservationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// login
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // "student", "teacher", หรือ "staff" ตามที่ออกแบบไว้
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetRoomScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // format: "2026-05-08"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomScheduleRequest) Reset() {
	*x = GetRoomScheduleRequest{}
	mi := &file_proto_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomScheduleRequest) ProtoMessage() {}

func (x *GetRoomScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetRoomScheduleRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoomScheduleRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetRoomScheduleRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ScheduleSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeSlot      string                 `protobuf:"bytes,1,opt,name=time_slot,json=timeSlot,proto3" json:"time_slot,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                     // "available" หรือ "booked"
	BookedBy      string                 `protobuf:"bytes,3,opt,name=booked_by,json=bookedBy,proto3" json:"booked_by,omitempty"` // user_id ถ้า booked, ว่างถ้า available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleSlot) Reset() {
	*x = ScheduleSlot{}
	mi := &file_proto_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleSlot) ProtoMessage() {}

func (x *ScheduleSlot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleSlot.ProtoReflect.Descriptor instead.
func (*ScheduleSlot) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{6}
}

func (x *ScheduleSlot) GetTimeSlot() string {
	if x != nil {
		return x.TimeSlot
	}
	return ""
}

func (x *ScheduleSlot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScheduleSlot) GetBookedBy() string {
	if x != nil {
		return x.BookedBy
	}
	return ""
}

type RoomScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Slots         []*ScheduleSlot        `protobuf:"bytes,3,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomScheduleResponse) Reset() {
	*x = RoomScheduleResponse{}
	mi := &file_proto_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomScheduleResponse) ProtoMessage() {}

func (x *RoomScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomScheduleResponse.ProtoReflect.Descriptor instead.
func (*RoomScheduleResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{7}
}

func (x *RoomScheduleResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomScheduleResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *RoomScheduleResponse) GetSlots() []*ScheduleSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

// ดูประวัติการจองของตนเอง
type MyReservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	TimeSlot      string                 `protobuf:"bytes,4,opt,name=time_slot,json=timeSlot,proto3" json:"time_slot,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyReservation) Reset() {
	*x = MyReservation{}
	mi := &file_proto_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyReservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyReservation) ProtoMessage() {}

func (x *MyReservation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyReservation.ProtoReflect.Descriptor instead.
func (*MyReservation) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{8}
}

func (x *MyReservation) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *MyReservation) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MyReservation) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MyReservation) GetTimeSlot() string {
	if x != nil {
		return x.TimeSlot
	}
	return ""
}

func (x *MyReservation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MyReservationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*MyReservation       `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyReservationsResponse) Reset() {
	*x = MyReservationsResponse{}
	mi := &file_proto_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyReservationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyReservationsResponse) ProtoMessage() {}

func (x *MyReservationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyReservationsResponse.ProtoReflect.Descriptor instead.
func (*MyReservationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{9}
}

func (x *MyReservationsResponse) GetReservations() []*MyReservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type CancelReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationRequest) Reset() {
	*x = CancelReservationRequest{}
	mi := &file_proto_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationRequest) ProtoMessage() {}

func (x *CancelReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{10}
}

func (x *CancelReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CancelReservationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationResponse) Reset() {
	*x = CancelReservationResponse{}
	mi := &file_proto_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationResponse) ProtoMessage() {}

func (x *CancelReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationResponse.ProtoReflect.Descriptor instead.
func (*CancelReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{11}
}

func (x *CancelReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelReservationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{12}
}

type RoomList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomList) Reset() {
	*x = RoomList{}
	mi := &file_proto_booking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomList) ProtoMessage() {}

func (x *RoomList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomList.ProtoReflect.Descriptor instead.
func (*RoomList) Descriptor() ([]byte, []int) {
	return file_proto_booking_proto_rawDescGZIP(), []int{13}
}

func (x *RoomList) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_proto_booking_proto protoreflect.FileDescriptor

const file_proto_booking_proto_rawDesc = "" +
	"\n" +
	"\x13proto/booking.proto\x12\abooking\"F\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\"w\n" +
	"\x12ReservationRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttime_slot\x18\x03 \x01(\tR\btimeSlot\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\"n\n" +
	"\x13ReservationResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"F\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"E\n" +
	"\x16GetRoomScheduleRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"`\n" +
	"\fScheduleSlot\x12\x1b\n" +
	"\ttime_slot\x18\x01 \x01(\tR\btimeSlot\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tbooked_by\x18\x03 \x01(\tR\bbookedBy\"p\n" +
	"\x14RoomScheduleResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12+\n" +
	"\x05slots\x18\x03 \x03(\v2\x15.booking.ScheduleSlotR\x05slots\"\x98\x01\n" +
	"\rMyReservation\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1b\n" +
	"\ttime_slot\x18\x04 \x01(\tR\btimeSlot\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"T\n" +
	"\x16MyReservationsResponse\x12:\n" +
	"\freservations\x18\x01 \x03(\v2\x16.booking.MyReservationR\freservations\"Z\n" +
	"\x18CancelReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"O\n" +
	"\x19CancelReservationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\a\n" +
	"\x05Empty\"/\n" +
	"\bRoomList\x12#\n" +
	"\x05rooms\x18\x01 \x03(\v2\r.booking.RoomR\x05rooms2\xbc\x03\n" +
	"\x0eBookingService\x126\n" +
	"\x05Login\x12\x15.booking.LoginRequest\x1a\x16.booking.LoginResponse\x12-\n" +
	"\bGetRooms\x12\x0e.booking.Empty\x1a\x11.booking.RoomList\x12N\n" +
	"\x11CreateReservation\x12\x1b.booking.ReservationRequest\x1a\x1c.booking.ReservationResponse\x12Q\n" +
	"\x0fGetRoomSchedule\x12\x1f.booking.GetRoomScheduleRequest\x1a\x1d.booking.RoomScheduleResponse\x12D\n" +
	"\x11GetMyReservations\x12\x0e.booking.Empty\x1a\x1f.booking.MyReservationsResponse\x12Z\n" +
	"\x11CancelReservation\x12!.booking.CancelReservationRequest\x1a\".booking.CancelReservationResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_booking_proto_rawDescOnce sync.Once
	file_proto_booking_proto_rawDescData []byte
)

func file_proto_booking_proto_rawDescGZIP() []byte {
	file_proto_booking_proto_rawDescOnce.Do(func() {
		file_proto_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_booking_proto_rawDesc), len(file_proto_booking_proto_rawDesc)))
	})
	return file_proto_booking_proto_rawDescData
}

var file_proto_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_booking_proto_goTypes = []any{
	(*Room)(nil),                      // 0: booking.Room
	(*ReservationRequest)(nil),        // 1: booking.ReservationRequest
	(*ReservationResponse)(nil),       // 2: booking.ReservationResponse
	(*LoginRequest)(nil),              // 3: booking.LoginRequest
	(*LoginResponse)(nil),             // 4: booking.LoginResponse
	(*GetRoomScheduleRequest)(nil),    // 5: booking.GetRoomScheduleRequest
	(*ScheduleSlot)(nil),              // 6: booking.ScheduleSlot
	(*RoomScheduleResponse)(nil),      // 7: booking.RoomScheduleResponse
	(*MyReservation)(nil),             // 8: booking.MyReservation
	(*MyReservationsResponse)(nil),    // 9: booking.MyReservationsResponse
	(*CancelReservationRequest)(nil),  // 10: booking.CancelReservationRequest
	(*CancelReservationResponse)(nil), // 11: booking.CancelReservationResponse
	(*Empty)(nil),                     // 12: booking.Empty
	(*RoomList)(nil),                  // 13: booking.RoomList
}
var file_proto_booking_proto_depIdxs = []int32{
	6,  // 0: booking.RoomScheduleResponse.slots:type_name -> booking.ScheduleSlot
	8,  // 1: booking.MyReservationsResponse.reservations:type_name -> booking.MyReservation
	0,  // 2: booking.RoomList.rooms:type_name -> booking.Room
	3,  // 3: booking.BookingService.Login:input_type -> booking.LoginRequest
	12, // 4: booking.BookingService.GetRooms:input_type -> booking.Empty
	1,  // 5: booking.BookingService.CreateReservation:input_type -> booking.ReservationRequest
	5,  // 6: booking.BookingService.GetRoomSchedule:input_type -> booking.GetRoomScheduleRequest
	12, // 7: booking.BookingService.GetMyReservations:input_type -> booking.Empty
	10, // 8: booking.BookingService.CancelReservation:input_type -> booking.CancelReservationRequest
	4,  // 9: booking.BookingService.Login:output_type -> booking.LoginResponse
	13, // 10: booking.BookingService.GetRooms:output_type -> booking.RoomList
	2,  // 11: booking.BookingService.CreateReservation:output_type -> booking.ReservationResponse
	7,  // 12: booking.BookingService.GetRoomSchedule:output_type -> booking.RoomScheduleResponse
	9,  // 13: booking.BookingService.GetMyReservations:output_type -> booking.MyReservationsResponse
	11, // 14: booking.BookingService.CancelReservation:output_type -> booking.CancelReservationResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_booking_proto_init() }
func file_proto_booking_proto_init() {
	if File_proto_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_booking_proto_rawDesc), len(file_proto_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_booking_proto_goTypes,
		DependencyIndexes: file_proto_booking_proto_depIdxs,
		MessageInfos:      file_proto_booking_proto_msgTypes,
	}.Build()
	File_proto_booking_proto = out.File
	file_proto_booking_proto_goTypes = nil
	file_proto_booking_proto_depIdxs = nil
}
